import * as yup from "yup";

export const _initialValues = {
  mobileLogo: [],
  helpLineNumber: "",
  helpEmail: "",
  onboardingImage1: [],
  onboardingImage2: [],
  onboardingImage3: [],
  onboardingContent1: "",
  onboardingContent2: "",
  onboardingContent3: "",
  instagramLink: "",
  whatsappLink: "",
  facebookLink: "",
  youtubeLink: "",
  linkedinLink: "",
  HeaderIcon: [],
  applicationName: "",
  tagLine: "",
  socialcontent: "",
  androidMobileVersion: "",
  iosMobileVersion: "",
  androidAppUrl: "",
  iosAppUrl: "",
  studentAndroidMobileVersion: '',
  studentIosMobileVersion: '',
  parentAndroidMobileVersion: '',
  parentIosMobileVersion: '',
  parentPrimaryColor: '',
  parentSecondaryColor: '',
  parentBgColor: '',
  studentPrimaryColor: '',
  studentSecondaryColor: '',
  studentBgColor: '',

};

export const MobileValidate = yup.object().shape({
  mobileLogo: yup.array().min(1, "Field is required"),
  // helpLineNumber: yup.string().required("Field is required"),
  // helpEmail: yup.string().required("Field is required"),
  onboardingImage1: yup.array().min(1, "Field is required"),
  onboardingImage2: yup.array().min(1, "Field is required"),
  onboardingImage3: yup.array().min(1, "Field is required"),
  onboardingContent1: yup.string().required("Field is required"),
  onboardingContent2: yup.string().required("Field is required"),
  onboardingContent3: yup.string().required("Field is required"),
  // instagramLink: yup.string().required("Field is required"),
  // whatsappLink: yup.string().required("Field is required"),
  // facebookLink: yup.string().required("Field is required"),
  // youtubeLink: yup.string().required("Field is required"),
  // linkedinLink: yup.string().required("Field is required"),
  HeaderIcon: yup.array().min(1, "Field is required"),
  applicationName: yup.string().required("Field is required"),
  // tagline: yup.string().required("Field is required"),
});
